#so to say the root directory
projectsepicsupstream=~/projects/epics/upstream

#Where should all git/hg/bzr live
projectsepicsgit=$projectsepicsupstream/git
projectsepicshg=$projectsepicsupstream/hg
projectsepicsbzr=$projectsepicsupstream/bzr
localSVNmirrors=$projectsepicsupstream/localSVNmirrors

#Where is epics base
projectsepicsgitbase=$projectsepicsgit/base
projectsepicsbzrbase=$projectsepicsbzr/base


#Where is epics 4
projectsepicsgitepics4=$projectsepicsgit/epics4
projectsepicshgepics4=$projectsepicshg/epics4


