#so to say the root directory
homeepicsupstream=~/epics/upstream

#Where should all git/hg/bzr live
homeepicsgit=$homeepicsupstream/git
homeepicshg=$homeepicsupstream/hg
homeepicsbzr=$homeepicsupstream/bzr
localSVNmirrors=$homeepicsupstream/localSVNmirrors

#Where is epics base
homeepicsgitbase=$homeepicsgit/base
homeepicsbzrbase=$homeepicsbzr/base


#Where is epics 4
homeepicsgitepics4=$homeepicsgit/epics4
homeepicshgepics4=$homeepicshg/epics4


